name: Tests

on: [push, pull_request]

jobs:
  unit-tests:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.3'
        enable-stack: true
        stack-version: 'latest'

    - name: Unit tests
      run: |
        cabal clean
        cabal test --test-show-details=direct