name: Tests

on: [push, pull_request]

jobs:
  unit-tests:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '9.0.2'
        cabal-version: 'latest'

    - name: Dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    
    - name: Build
      run: |
        cabal build --enable-tests --enable-benchmarks all

    - name: Unit tests
      run: |
        cabal test --test-show-details=direct all